Homepage.class: Homepage.java User.class Checking.class Saving.class Admin.class
	javac Homepage.java

User.class: User.java
	javac User.java

Checking.class: Checking.java
	javac Checking.java

Saving.class: Saving.java
	javac Saving.java

Admin.class: Admin.java
	javac Admin.java
clean: 
	rm *.class

run: Homepage.class
	java Homepage
